api:
    prefix:   /api
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin