# Bundles
# =======

# Application Programming Interface
# ---------------------------------
api:

    prefix:   /api
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest

# Application
# -----------

app:
    resource: "@AppBundle/Controller/"
    type:     annotation