# FOSRestBundle
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: "force"
        force_redirects:
            html: false
        formats:
            json:  true
            jsonp: true
            xml:   true
        templating_formats:
            html: true
        jsonp_handler: ~
        default_engine: twig
    exception:
        codes:
            "Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException": 404
            "Doctrine\\ORM\\OptimisticLockException": HTTP_CONFLICT
    routing_loader:
            default_format: json
            include_format: true

# Nelmio ApiDocBundle
nelmio_api_doc:
    name: "ArteBlog API documentation"
    sandbox:
        accept_type: application/json

# Nelmio CorsBundle
nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: "*"
#        allow_headers: []
#        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
#        expose_headers: []
#        max_age: 0
#        hosts: []
    paths:
        "^/api/":
            allow_origin: "*"
            allow_headers: ["X-Custom-Auth", "Authorization", "Content-Type"]
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
            expose_headers: ["Location"]
            max_age: 3600